### ISSUE TITLE
Alterar view de Login, padronizando o "Bem vindo"

### ISSUE THREAD

**Issue by gabrielgrs** [Silvinha01/ProjetoES2-12082016#44]

**Comment by masmangan** [comment]
https://www.priberam.pt/dlpo/bem-vindo

**Comment by masmangan** [comment]
http://educacao.uol.com.br/portugues/reforma-ortografica/2009/01/30/minivocabulario.jhtm

**Comment by Tales77** [comment]
Olá professor,

Sobre a palavra bem-vindo, foi o que eu disse para o colega Gabriel,
mostrando-lhe a forma correta da grafia. Segundo ele, para sistemas nao se
usa essa grafia por se tratar de uma grafia "arcaica", e que era melhor eu
ir por ele. Não concordei, mas segui o que ele disse para fazer.
